// app/layout.tsx

// Importing necessary types and components
import type { Metadata } from 'next'; // Type for metadata
import { Inter as FontSans } from 'next/font/google'; // Google Font
import './globals.css'; // Global CSS styles
import { cn } from '@/lib/utils'; // Utility function for class names
import ToastContainerWrapper from '@/components/ui/toast'; // Toast container component
import 'react-toastify/dist/ReactToastify.css'; // CSS for react-toastify

// Initializing the Inter font with specific subsets and a CSS variable
export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

// Metadata for the application
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// RootLayout component
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased', // Tailwind CSS classes
          fontSans.variable // Applying the font variable
        )}
      >
        {children} {/* Rendering child components */}
        <ToastContainerWrapper /> {/* Toast notifications */}
      </body>
    </html>
  );
}
